// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Command Wrap")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Crabwise Studios")]
[assembly: AssemblyProduct("Crabwise.CommandWrap.Properties")]
[assembly: AssemblyCopyright("2010 Crabwise Studios")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("05485205-ce27-4dc9-a087-499b93dd63fb")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Crabwise.CommandWrap.UnitTests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100a16422aecc10ac3ef47ffad32b0679c68ddc97c595573264f520437ce0ea3a3c5c19dfe0ecef252016adebfedbb39bcfe9f7b35d3801505709b1107e85cdd5a4696725ff7b88216c60791d66eed5ea55fe582e2184b2d429820953b5e8494070f0d75cae9c6780e6de432934fc6c8f553b3d9a6ce6c7c5d1db6ed58dce4aeaa1")]